---
glaciers:
  RGI60-11.00897:
    name: 'Hintereisferner'
    WGMS_ID: 491
    flowline_params:
      T0: 22.27
      P0: 1.5
      L0:
        value: 10250 
        year: 1855
      ss_noise_profile: "features/flowline/flowline2d_RGI60-11.00897.ss.noise.pickle"
  RGI60-11.03638:  # argentiere
    name: 'Argentiere'
    flowline_params:
      T0: 10
  RGI60-02.18778:  # south cascade
    name: 'South Cascade'
    flowline_params:
      sigT: 1
      T0: 16.28
      sigP: 0
      P0: 2.5
      L0:
        value: 4450
        year: 1850
      ss_noise_profile: "features/flowline/flowline2d_RGI60-02.18778.ss.noise.pickle"
  RGI60-01.09162:  # wolverine
    name: 'Wolverine'
    flowline_params: 
      T0: 13.68
      P0: 3.5
      ss_noise_profile: "features/flowline/flowline2d_RGI60-01.09162.ss.noise.pickle"
  RGI60-01.00570:
    name: 'Gulkana'
    flowline_params:
  RGI60-11.01450:
    name: 'Aletch'
    flowline_params:
  RGI60-11.01346:
    name: 'Unterer Grindelwald'
  RGI60-11.01238:
    name: 'Rhone'
  RGI60-11.03646:
    name: 'Bossons'
  RGI60-11.03643:
    name: 'Mer de Glace'